apiVersion: v2
name: specify7
description: A Helm chart for deploying Specify 7 on Kubernetes
type: application
version: 0.1.0
appVersion: "v0.1.0"
dependencies:
  - name: mariadb
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common


